##' GSEA plot that mimic the plot generated by broad institute's GSEA software
##'
##'
##' @title GSEAplot2
##' @param x gseaResult object
##' @param geneSetID gene set ID
##' @param title plot title
##' @param color color of running enrichment score line
##' @param base_size base font size
##' @param rel_heights relative heights of subplots
##' @param subplots which subplots to be displayed
##' @param ES_geom geom for plotting running enrichment score,one of 'line' or 'dot'
##' @param Type A character vector indicating the type.Type can length from 2 to 5,eg Type=c("Wild", "Mut");(default = Type[[1]] is the control)
##' @param legend.position legend.position=c("top","bottom","right","left","none")
##' @param pvalue_table	 whether add pvalue table, defalut pvalue_table=TRUE
##' @return plot
##' @export
##' @importFrom ggplot2 theme_classic
##' @importFrom ggplot2 element_line
##' @importFrom ggplot2 element_text
##' @importFrom ggplot2 element_blank
##' @importFrom ggplot2 element_rect
##' @importFrom ggplot2 scale_x_continuous
##' @importFrom ggplot2 scale_y_continuous
##' @importFrom ggplot2 scale_color_manual
##' @importFrom ggplot2 theme_void
##' @importFrom ggplot2 geom_rect
##' @importFrom ggplot2 margin
##' @importFrom ggplot2 annotation_custom
##' @importFrom stats quantile
##' @importFrom RColorBrewer brewer.pal
##' @author Pengmin Yang
GSEAplot2 <- function(x, geneSetID = c(1:10), title = "", color = ggsci::pal_gsea()(10), base_size = 11,
                      rel_heights = c(1.5, 0.5, 1), subplots = 1:3, legend.position = "right",
                      ES_geom = "line", pvalue_table=TRUE,Type) {
  ES_geom <- match.arg(ES_geom, c("line", "dot"))
  geneList <- position <- NULL
  #
  gsInfo <- function(object, geneSetID) {
    geneList <- object@geneList
    gseaScores <- getFromNamespace("gseaScores", "DOSE")
    if (is.numeric(geneSetID))
      geneSetID <- object@result[geneSetID, "ID"]
    geneSet <- object@geneSets[[geneSetID]]
    exponent <- object@params[["exponent"]]
    df <- gseaScores(geneList, geneSet, exponent, fortify=TRUE)
    df$ymin <- 0
    df$ymax <- 0
    pos <- df$position == 1
    h <- diff(range(df$runningScore))/20
    df$ymin[pos] <- -h
    df$ymax[pos] <- h
    df$geneList <- geneList
    if (length(object@gene2Symbol) == 0) {
      df$gene <- names(geneList)
    } else {
      df$gene <- object@gene2Symbol[names(geneList)]
    }

    df$Description <- object@result[geneSetID, "Description"]
    return(df)
  }
  #
  if (length(geneSetID) == 1) {
    gsdata <- gsInfo(x, geneSetID)
  } else {
    gsdata <- do.call(rbind, lapply(geneSetID, gsInfo, object = x))
  }

  p <- ggplot(gsdata, aes(x = x)) + xlab(NULL) + theme_classic(base_size) +
    theme(panel.grid.major = element_line(colour = "grey92"),
          panel.grid.minor = element_line(colour = "grey92"),
          panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank()) +
    scale_x_continuous(expand = c(0, 0))
  if (ES_geom == "line") {
    es_layer <- geom_line(aes(y = runningScore, color = Description),
                          linewidth = 1)
  } else {
    es_layer <- geom_point(aes(y = runningScore, color = Description),
                           size = 1, data = subset(gsdata, position == 1))
  }

  p.res <- p + es_layer + theme(legend.position = legend.position, legend.justification="center" ,
                                legend.box = "vertical",
                                legend.title = element_blank(),
                                legend.background = element_rect(fill = "transparent"))+
    scale_color_discrete(labels = function(x) str_wrap(x, width = 20))
  p.res <- p.res + ylab("Running Enrichment Score") + theme(axis.text.x = element_blank(),
                                                            axis.ticks.x = element_blank(), axis.line.x = element_blank(),
                                                            plot.margin = margin(t = 0.2, r = 0.2, b = 0, l = 0.2,
                                                                                 unit = "cm"))

  i <- 0
  for (term in unique(gsdata$Description)) {
    idx <- which(gsdata$ymin != 0 & gsdata$Description ==
                   term)
    gsdata[idx, "ymin"] <- i
    gsdata[idx, "ymax"] <- i + 1
    i <- i + 1
  }

  p2 <- ggplot(gsdata, aes(x = x)) + geom_linerange(aes(ymin = ymin,
                                                        ymax = ymax, color = Description)) + xlab(NULL) + ylab(NULL) +
    theme_classic(base_size) + theme(legend.position = "none",
                                     plot.margin = margin(t = -0.1, b = 0, unit = "cm"), axis.ticks = element_blank(),
                                     axis.text = element_blank(), axis.line.x = element_blank()) +
    scale_x_continuous(expand = c(0,
                                  0))

  if (length(geneSetID) == 1) {
    v <- seq(1, sum(gsdata$position), length.out = 9)
    inv <- findInterval(rev(cumsum(gsdata$position)), v)
    if (min(inv) == 0)
      inv <- inv + 1
    col <- c(rev(brewer.pal(5, "Blues")), brewer.pal(5, "Reds"))
    ymin <- min(p2$data$ymin)
    yy <- max(p2$data$ymax - p2$data$ymin) * 0.3
    xmin <- which(!duplicated(inv))
    xmax <- xmin + as.numeric(table(inv)[as.character(unique(inv))])
    d <- data.frame(ymin = ymin, ymax = yy, xmin = xmin,
                    xmax = xmax, col = col[unique(inv)])
    p2 <- p2 + geom_rect(aes(xmin = xmin, xmax = xmax,
                             ymin = ymin, ymax = ymax, fill = I(col)), data = d,
                         alpha = 0.9, inherit.aes = FALSE)
  }

  df2 <- p$data
  df2$y <- p$data$geneList[df2$x]
  p.pos <- p + geom_segment(data = df2, aes(x = x, xend = x,
                                            y = y, yend = 0), color = "#FFA500")
  p.pos <- p.pos + ylab("Ranked List Metric") + xlab("Rank in Ordered Dataset") +
    theme(plot.margin = margin(t = -0.1, r = 0.2, b = 0.2,
                               l = 0.2, unit = "cm"))

  y.max <- max(df2$y)
  y.min <- min(df2$y)
  x.max <- max(df2$x)
  x.min <- min(df2$x)
  p.pos <- p.pos + geom_text(data = data.frame(x = x.min+10, y = y.max, label = Type[[1]]),
                             mapping = aes(x = x, y = y, label = label), inherit.aes = F,check_overlap=F,hjust=0)
  p.pos <- p.pos + geom_text(data = data.frame(x = x.max, y = y.min, label = Type[[2]]),
                             mapping = aes(x = x, y = y, label = label), inherit.aes = F,check_overlap=F,hjust=1)
  if (!is.null(title) && !is.na(title) && title != "")
    p.res <- p.res + ggtitle(title)

  if (length(color) == length(geneSetID)) {
    p.res <- p.res + scale_color_manual(values = color)
    if (length(color) == 1) {
      p.res <- p.res + theme(legend.position.inside = "none")
      p2 <- p2 + scale_color_manual(values = "black")
    } else {
      p2 <- p2 + scale_color_manual(values = color)
    }
  }
  if (pvalue_table) {
    pd<-x@result[geneSetID, c("Description", "pvalue","NES")]
    rownames(pd) <- pd$Description
    pd <- pd[, -1]
    for (i in seq_len(ncol(pd))) {
      pd[, i] <- format(pd[, i], digits = 4)
    }
    tp <- enrichplot::ggtable(pd,p.res)
    tp <-ggplotify::as.grob(tp)
    p.res <- p.res + theme(legend.position = legend.position) + annotation_custom(tp,
                                                                                  xmin = quantile(p.res$data$x, 0.5), xmax = quantile(p.res$data$x,
                                                                                                                                      0.95), ymin = quantile(p.res$data$runningScore,
                                                                                                                                                             0.75), ymax = quantile(p.res$data$runningScore,
                                                                                                                                                                                    0.9))
  }else{
    pd<-x@result[geneSetID, c("Description", "pvalue","NES")]
    rownames(pd) <- pd$Description
    for(i in 1:nrow(pd)){
      label = paste(pd[i,1],paste0("(",paste0("pvalue = ",round(pd[i,2],6)),",",paste0("NES = ",round(pd[i,3],6)),")"))
      p2 <- p2 + geom_label(data = data.frame(x = quantile(df2$x)[[1]]+10, y = i-1, label = label),
                            mapping = aes(x = x, y = y, label = label),
                            inherit.aes = FALSE,
                            hjust = 0,vjust = 0,
                            fill = "#F7F7F7",
                            alpha = 0.8,    # 设置透明度
                            label.size = 0) # 设置边框大小为0，即去除边框
      cat("\033[31m", label, "\033[0m\n")
    }
  }
  plotlist <- list(p.res, p2, p.pos)[subplots]
  n <- length(plotlist)
  plotlist[[n]] <- plotlist[[n]] + theme(axis.line.x = element_line(),
                                         axis.ticks.x = element_line(), axis.text.x = element_text())

  if (length(subplots) == 1)
    return(plotlist[[1]] + theme(plot.margin = margin(t = 0.2,
                                                      r = 0.2, b = 0.2, l = 0.2, unit = "cm")))

  if (length(rel_heights) > length(subplots))
    rel_heights <- rel_heights[subplots]

  aplot::gglist(gglist = plotlist, ncol = 1, heights = rel_heights)
}

